services:
  db:
    image: postgres:14-alpine
    container_name: centro_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-centro_formacion}
      POSTGRES_USER: ${DB_USERNAME:-usuario}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "49000:5432" # o el puerto que prefieras
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-usuario} -d ${DB_DATABASE:-centro_formacion}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: centro_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000" # PHP artisan serve
      - "5173:5173" # Vite o PHP artisan serve
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
volumes:
  db_data:
